name: build

on:
  push: 
    branches:
      - main
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin]
        arch: [amd64, arm64]
    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Set up Go
      id: setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.0
    - run: go version
    
    - name: Install dependencies
      id: install
      run: go mod tidy
    
    - name: Cache Go modules
      id: cache
      uses: actions/cache@v2
      env:
        cache-name: cache-go-modules
      with: 
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-          

    - name: Build
      id: build
      run: make build GO_TARGET_OS=${{ matrix.os }} GO_TARGET_ARCH=${{ matrix.arch }}
