name: main

on:
  push:
    tags:
      - "v*.*.*"


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      id: setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.0
    - run: go version
    
    - name: Install dependencies
      id: install
      run: go mod tidy

    - name: Build
      id: build
      run: make build
    
    - name: Get Version
      id: version
      uses: ashley-taylor/read-json-property-action@v1.0
      with:
        path: package.json
        property: version

    - name: Compress binaries
      id: compress
      uses: svenstaro/upx-action@v2
      with:
        files: |
          prompt-manager

    - name: Archive
      id: archive
      run: make archive

    - name: Create Release
      id: create_release
      uses:  softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          prompt-manager.alfredworkflow

    # - name: Upload Artifact
    #   id: upload-artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: prompt-manager.alfredworkflow
    #     path: ./prompt-manager.alfredworkflow

        